//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorLocalizationDemo.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BlazorLocalizationDemo.Resources.App_en_US", typeof(App_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HomeSubtitle {
            get {
                return ResourceManager.GetString("HomeSubtitle", resourceCulture);
            }
        }
        
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        internal static string SurveyPromptTitle {
            get {
                return ResourceManager.GetString("SurveyPromptTitle", resourceCulture);
            }
        }
        
        internal static string CounterButton {
            get {
                return ResourceManager.GetString("CounterButton", resourceCulture);
            }
        }
        
        internal static string CounterText {
            get {
                return ResourceManager.GetString("CounterText", resourceCulture);
            }
        }
        
        internal static string CounterTitle {
            get {
                return ResourceManager.GetString("CounterTitle", resourceCulture);
            }
        }
        
        internal static string FetchDataDate {
            get {
                return ResourceManager.GetString("FetchDataDate", resourceCulture);
            }
        }
        
        internal static string FetchDataSubtitle {
            get {
                return ResourceManager.GetString("FetchDataSubtitle", resourceCulture);
            }
        }
        
        internal static string FetchDataSummary {
            get {
                return ResourceManager.GetString("FetchDataSummary", resourceCulture);
            }
        }
        
        internal static string FetchDataTempC {
            get {
                return ResourceManager.GetString("FetchDataTempC", resourceCulture);
            }
        }
        
        internal static string FetchDataTempF {
            get {
                return ResourceManager.GetString("FetchDataTempF", resourceCulture);
            }
        }
        
        internal static string FetchDataTitle {
            get {
                return ResourceManager.GetString("FetchDataTitle", resourceCulture);
            }
        }
        
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        internal static string NavBarApplicationName {
            get {
                return ResourceManager.GetString("NavBarApplicationName", resourceCulture);
            }
        }
        
        internal static string NavBarCounter {
            get {
                return ResourceManager.GetString("NavBarCounter", resourceCulture);
            }
        }
        
        internal static string NavBarFetchData {
            get {
                return ResourceManager.GetString("NavBarFetchData", resourceCulture);
            }
        }
        
        internal static string NavBarHome {
            get {
                return ResourceManager.GetString("NavBarHome", resourceCulture);
            }
        }
        
        internal static string HomeFooter1 {
            get {
                return ResourceManager.GetString("HomeFooter1", resourceCulture);
            }
        }
        
        internal static string HomeFooter2 {
            get {
                return ResourceManager.GetString("HomeFooter2", resourceCulture);
            }
        }
        
        internal static string HomeFooter3 {
            get {
                return ResourceManager.GetString("HomeFooter3", resourceCulture);
            }
        }
        
        internal static string SurveyTitle {
            get {
                return ResourceManager.GetString("SurveyTitle", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string AppNotFound {
            get {
                return ResourceManager.GetString("AppNotFound", resourceCulture);
            }
        }
        
        internal static string AppNotFoundSubtitle {
            get {
                return ResourceManager.GetString("AppNotFoundSubtitle", resourceCulture);
            }
        }
    }
}
